set nocompatible
filetype on

"https://github.com/gmarik/Vundle.vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"this is required for Vundle
Plugin 'gmarik/Vundle.vim' "https://github.com/VundleVim/Vundle.vim
Plugin 'Valloric/YouCompleteMe' "https://github.com/Valloric/YouCompleteMe
Plugin 'scrooloose/nerdtree' "https://github.com/scrooloose/nerdtree
Plugin 'terryma/vim-multiple-cursors' "https://github.com/terryma/vim-multiple-cursors

call vundle#end()
filetype plugin indent on

set history=50 "50 lines of command line history
set ruler      "show the cursor pistion all times
set showcmd    "display incomplete commands
set incsearch  "do incremental searching
set showmatch  "show matching parens

"FORMATING
set number

"set tabstop and turn into softabs
set tabstop=4
set expandtab
"indentation shift amount
set shiftwidth=4

"keep highlighting on
set hlsearch

"wrap text after certain number of characters
autocmd BufRead,BufNewFile * set textwidth=80

"Turn off comment formatting options
"c auto insert comment leader when wrapping bsed on textwidth
"o insert comment leader when using o or O
"r insert coment leader when hitting <Enter> in insert mode
autocmd BufRead,BufNewFile * set formatoptions-=c formatoptions -=o formatoptions -=r

"COLORS
syntax on
color ryslate
"Theme here:
set cc=80
:hi ColorColumn ctermbg=DarkGray

set cursorline

"highlight bad whitespace
highlight BadWhitespace ctermbg=red guibg=red
"makes tabs in beginning of line in Python bad whitespace
autocmd BufRead,BufNewFile *.py match BadWhitespace /^\t+/
"makes trailing whitespace in all lanugages bad
autocmd BufRead,BufNewFile * match BadWhitespace /\s\+$/

"Searching for highlighted text
vnoremap // y/<C-R>"<CR>
"F2 in command mode now prints the file name
map <F2> :echo @%<CR>
"F3 runs pwd
map <F3> :pwd<CR>
"F4 gets absolute path
map <F4> :echo expand('%:p')<CR>
"F5 is nerd tree
map <F5> :NERDTree<CR>
"F12 runs taglist
nnoremap <silent> <F12> :TlistToggle<CR>

"PREVIEW WINDOWS
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
