# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
export LC_ALL="en_US.UTF-8"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ryfletcherm"

# Urncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).

# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"
#configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install

# # The following lines were added by compinstall
# zstyle :compinstall filename '/home/ryan/.zshrc'
#
# autoload -Uz compinit
# compinit
# # End of lines added by compinstall
# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# git - automatically added
# history-substring-search - inside of oh my zsh already
# syntax highlighting: https://github.com/zsh-users/zsh-syntax-highlighting
# zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
# alias-tips: https://github.com/djui/alias-tips
plugins=(git history-substring-search zsh-autosuggestions alias-tips)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$HOME/Programs/android-studio/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R'
alias less='less -N'
alias ls="ls -X --group-directories-first --color=auto"
alias spellcheck="aspell --check"
alias spell="saspell"
alias mkdir="mkdir -p"
alias runctags="ctags -R -f tags ."
alias netrw="vim ."
alias alert='notify-send --urgency=low -i "$( [ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias running='ps -ax | grep -v "grep" | grep -i '
alias reademail='mbsync emc && mutt'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# setup calculator alais
autoload -U zcalc
function __call_zcalc {
    zcalc -e "$*"
}
aliases[calc]='__call_zcalc'

# enable syntax highlighting
source ~/.oh-my-zsh/plugins/syntax/zsh-syntax-highlighting.zsh
# custom highlighting for zsh syntax highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
ZSH_HIGHLIGHT_STYLES[command]="fg=green"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=green"
ZSH_HIGHLIGHT_STYLES[alias]="fg=green"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=green,bold"
ZSH_HIGHLIGHT_STYLES[hashed-command]="fg=green"
ZSH_HIGHLIGHT_STYLES[function]="fg=green"
ZSH_HIGHLIGHT_STYLES[path]="fg=cyan"
ZSH_HIGHLIGHT_STYLES[path_prefix]="fg=cyan,underline"
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=white"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=white"
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]="fg=yellow"

bindkey -v
# make switching modes more responsive
export KEYTIMEOUT=1
# reset some keybondings that are changed by vim mode
bindkey '^P' up-history
bindkey '^N' down-history
# default to insert mode
VIMMODE='[i]'
# callback for mode change
function zle-keymap-select {
  VIMMODE="${${KEYMAP/vicmd/[n]}/(main|viins)/[i]}"
  zle reset-prompt
}
zle -N zle-keymap-select

# print date info
cal

